### ISSUE TITLE
Debug Problem

### ISSUE THREAD

**Issue by wansenwu** [YicongHong/Discrete-Continuous-VLN#2]
Thanks for releasing the code of the dcvln, it is an very interesting job. I follow the instruction to run the source code, it works perfectly. But when I want to debug the code by Pycharm 2018 Pro, it gets stuck in 
`self.envs = construct_envs(
            self.config, get_env_class(self.config.ENV_NAME),
            episodes_allowed=episode_ids,
            auto_reset_done=False
        )`  in **ss_trainer_CMA.py line 361**, which is very weird. 
Specifically, I use the Debug in Pycharm IDE and run the code step by step, it always gets stuck in this line and no response at all. 
I guess the problem is due to the multiprocess, maybe certain subprocess is wait for interaction or something. I tried to go inside and found **habitat.VectorEnv()** is no response. Possibly, is it the problem of our computer or IDE? Does debug mode work well in your side?
I'm looking for your reply！

**Comment by wz0919** [comment]
Hi,

Did you get stuck only when building VectorEnv? Can you build only one environment using `examples/example.py` in [Habitat-lab](https://github.com/facebookresearch/habitat-lab)? If the problem is only about VectorEnv when debugging (which means you could successfully run the code in the terminal), maybe you could try using `habitat.ThreadedVectorEnv` to debug.

BTW, I used to use Pycharm to debug but I didn't meet this problem before. My Pycharm version is 2020 pro.

Cheers

**Comment by wansenwu** [comment]
> 

I change my pycharm from 18 to 22 pro, then the debug mode works normally! I waste many time focusing on the code, but never think about the problem of IDE because it works well on other codes.
Thanks again!
